import { Link } from 'react-router-dom'
import { ArrowLeft, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import { useCart } from '../context/CartContext'
import { formatPrice } from '../utils/format'

export default function Cart() {
  const { items, update, remove, clear } = useCart()
  const subtotal = items.reduce((sum, item) => sum + item.price * item.quantity, 0)
  if (!items.length) return <div className="container empty-cart"><div className="empty-cart-icon"><ShoppingBag size={34}/></div><p className="eyebrow">YOUR CART</p><h1>Your cart is empty</h1><p>Add a few products from the catalogue and they’ll appear here.</p><Link className="primary-btn" to="/">Start shopping</Link></div>
  return <div className="container cart-page"><Link className="back-link" to="/"><ArrowLeft size={16}/> Continue shopping</Link><div className="cart-heading"><div><p className="eyebrow">YOUR CART</p><h1>Ready when you are.</h1></div><button className="text-danger" onClick={clear}>Clear cart</button></div><div className="cart-layout"><section className="cart-items">{items.map((item) => <article className="cart-item" key={item.id}><Link to={`/product/${item.id}`} className="cart-thumb">{item.image ? <img src={item.image} alt=""/> : <ShoppingBag/>}</Link><div className="cart-item-info"><Link to={`/product/${item.id}`}><h3>{item.name}</h3></Link><p>{formatPrice(item.price)} each</p><div className="qty"><button onClick={() => update(item.id, item.quantity - 1)}><Minus size={15}/></button><strong>{item.quantity}</strong><button onClick={() => update(item.id, item.quantity + 1)}><Plus size={15}/></button></div></div><strong className="item-total">{formatPrice(item.price * item.quantity)}</strong><button className="icon-btn danger" aria-label="Remove item" onClick={() => remove(item.id)}><Trash2 size={18}/></button></article>)}</section><aside className="summary"><p className="eyebrow">ORDER SUMMARY</p><div className="summary-row"><span>Items</span><span>{items.reduce((s, i) => s + i.quantity, 0)}</span></div><div className="summary-row"><span>Subtotal</span><strong>{formatPrice(subtotal)}</strong></div><div className="summary-divider"/><div className="summary-row total"><span>Total</span><strong>{formatPrice(subtotal)}</strong></div><button className="primary-btn full" onClick={() => alert('Checkout is not part of the supplied backend yet.')}>Proceed to checkout</button><small>Checkout/payment endpoints are not present in the supplied backend, so this button is intentionally non-transactional.</small></aside></div></div>
}
