import { useEffect, useState } from 'react'
import { Edit3, Plus, Trash2, X, Package } from 'lucide-react'
import { getImageUrl, productApi } from '../services/api'
import ProductForm from '../components/ProductForm'
import { formatPrice } from '../utils/format'
import { getErrorMessage } from '../utils/errors'

export default function ManageProducts() {
  const [products, setProducts] = useState([]); const [editing, setEditing] = useState(null); const [showForm, setShowForm] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  async function load() { setLoading(true); setError(''); try { const res = await productApi.list(); setProducts((res.data || []).map((p) => ({ ...p, imageUrl: getImageUrl(p) }))) } catch (err) { setError(getErrorMessage(err, 'Unable to load products.')) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  async function submit(data, file) { setSaving(true); setError(''); try { if (editing) { await productApi.update(editing.id, data, file) ; setNotice('Product updated successfully.') } else { await productApi.create(data, file); setNotice('Product created successfully.') } setShowForm(false); setEditing(null); await load() } catch (err) { setError(getErrorMessage(err, 'Could not save product.')) } finally { setSaving(false) } }
  async function remove(id) { if (!window.confirm('Delete this product?')) return; setError(''); try { await productApi.remove(id); setNotice('Product deleted.'); await load() } catch (err) { setError(getErrorMessage(err, 'Could not delete product.')) } }
  return <div className="container manage-page"><div className="manage-head"><div><p className="eyebrow">STORE MANAGEMENT</p><h1>Products</h1><p className="muted">Create, update and remove products using the backend’s protected product APIs.</p></div><button className="primary-btn" onClick={() => { setEditing(null); setShowForm(true); setError('') }}><Plus size={18}/> Add product</button></div>{notice && <div className="form-success notice">{notice}<button onClick={() => setNotice('')}><X size={14}/></button></div>}{error && <div className="form-error notice">{error}</div>}{showForm && <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><p className="eyebrow">{editing ? 'EDIT PRODUCT' : 'NEW PRODUCT'}</p><h2>{editing ? 'Update product' : 'Create product'}</h2></div><button className="icon-btn" onClick={() => { setShowForm(false); setEditing(null) }}><X/></button></div><ProductForm initial={editing} onSubmit={submit} loading={saving} onCancel={() => { setShowForm(false); setEditing(null) }}/></div></div>}
    {loading ? <div className="manage-list">{Array.from({length:4}).map((_,i)=><div className="skeleton-row" key={i}/>)}</div> : <div className="manage-list">{products.map((p) => <article className="manage-row" key={p.id}><div className="manage-thumb">{p.imageUrl ? <img src={p.imageUrl} alt=""/> : <Package/>}</div><div className="manage-main"><strong>{p.name}</strong><span>{p.brand || '—'} · {p.category || '—'}</span></div><div className="manage-price">{formatPrice(p.price)}</div><div className="manage-stock">{p.productAvailable && p.stockQuantity > 0 ? `${p.stockQuantity} in stock` : 'Unavailable'}</div><div className="manage-actions"><button className="icon-btn" title="Edit" onClick={() => { setEditing(p); setShowForm(true) }}><Edit3 size={17}/></button><button className="icon-btn danger" title="Delete" onClick={() => remove(p.id)}><Trash2 size={17}/></button></div></article>)}{products.length === 0 && <div className="state-card"><strong>No products yet</strong><p>Create your first product to populate the storefront.</p></div>}</div>}
  </div>
}
